language: php
php:
  - 7.1
  - 7.2

services: mysql

os:
  - linux

matrix:
  allow_failures:
    - php: 7.2

cache:
  directories:
  - vendor

install: travis_retry composer install --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction

before_script:
  - git config --global user.email "kaireewu@gmail.com"
  - git config --global user.name "kairee Travis"
  - mysql -e 'CREATE DATABASE devfeed_test;'
  - cp -f .env.testing .env
  - php artisan key:generate

script: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
