language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'

services: mysql

cache:
  directories:
  - vendor

before_install:
  - mysql -e 'CREATE DATABASE devfeed_test;'

install: composer install --prefer-dist

before_script:
  - cp -f .env.testing .env
  - php artisan key:generate

script: vendor/bin/phpunit
