# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: phpunit/phpunit:6.0.6

pipelines:
  default:
    - step:
        script:
          - php -r "file_exists('.env') || copy('.env.testing', '.env');"
          - composer install
          - php artisan key:generate
          - phpunit