image: php:7-fpm

pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install -qy git curl mysql-client
          - docker-php-ext-install -j$(nproc) pdo_mysql
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - ./install-composer.sh
          - composer install
          - export DB_CONNECTION=mysql
          - php -r "file_exists('.env') || copy('.env.testing', '.env');"
          - php artisan migrate
          - php artisan serve &
          - vendor/bin/phpunit

definitions:
  services:
    mysql:
      image: mysql
      environment:
        MYSQL_DATABASE: 'homestead'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'homestead'
        MYSQL_PASSWORD: 'secret'
